name: Build
on:
  push:
    branches:
    - main
    - development
    - release
  pull_request:
    branches:
    - main
    - development
    - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: Build goNES
        run: |
          make goNES
