name: CICD
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: Install dependencies
        run: |
          make dependencies
      - name: Run vet & lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: Build goNES
        run: |
          make goNES
